version: '3'
services:
  topupweb:
    build: ./docker/nginx
    container_name: 'topup-web'
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
      - ./build:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '3000:3000'
    command: >
      sh -c "yarn --pure-lockfile && yarn build && nginx -g 'daemon off;'"
